version: '3.1'

services:
  db:
    image: postgres
    container_name: webflux-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: webflux-db
    ports:
      - "5432:5432"
    volumes:
      - webflux_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: webflux-adminer
    ports:
      - 8000:8080

volumes:
  webflux_data: